version: "3"
services:
  terraform-provider-massdriver:
    build:
      args:
        USER: $USER
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - MASSDRIVER_DEPLOYMENT_ID=deploy-ment-idfakefake-whatever
      - MASSDRIVER_TOKEN=s3cr3tT0k3n
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - CGO_ENABLED=0
    networks:
      provider: {}

networks:
  provider:
