// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// A key-value dimension identifying the cloud resource a metric applies to.
type AlarmMetricDimensionInput struct {
	// Dimension name as defined by the cloud provider.
	Name string `json:"name"`
	// Dimension value identifying the monitored resource.
	Value string `json:"value"`
}

// GetName returns AlarmMetricDimensionInput.Name, and is useful for accessing the field via an interface.
func (v *AlarmMetricDimensionInput) GetName() string { return v.Name }

// GetValue returns AlarmMetricDimensionInput.Value, and is useful for accessing the field via an interface.
func (v *AlarmMetricDimensionInput) GetValue() string { return v.Value }

// The cloud metric an alarm evaluates.
//
// Most fields are optional because availability depends on the cloud provider.
// Pass `dimensions: []` if the provider doesn't expose structured dimensions
// for this metric.
type AlarmMetricInput struct {
	// Cloud service namespace that categorizes the metric (e.g., `AWS/RDS`).
	Namespace string `json:"namespace,omitempty"`
	// Metric name within the namespace (e.g., `CPUUtilization`).
	Name string `json:"name,omitempty"`
	// Aggregation function applied to samples (e.g., `Average`). Optional for providers without it.
	Statistic string `json:"statistic,omitempty"`
	// Cloud region the metric is scoped to, when applicable.
	Region string `json:"region,omitempty"`
	// Dimensions identifying the monitored resource. Omit or pass an empty list when the cloud provider doesn't expose structured dimensions.
	Dimensions []AlarmMetricDimensionInput `json:"dimensions,omitempty"`
}

// GetNamespace returns AlarmMetricInput.Namespace, and is useful for accessing the field via an interface.
func (v *AlarmMetricInput) GetNamespace() string { return v.Namespace }

// GetName returns AlarmMetricInput.Name, and is useful for accessing the field via an interface.
func (v *AlarmMetricInput) GetName() string { return v.Name }

// GetStatistic returns AlarmMetricInput.Statistic, and is useful for accessing the field via an interface.
func (v *AlarmMetricInput) GetStatistic() string { return v.Statistic }

// GetRegion returns AlarmMetricInput.Region, and is useful for accessing the field via an interface.
func (v *AlarmMetricInput) GetRegion() string { return v.Region }

// GetDimensions returns AlarmMetricInput.Dimensions, and is useful for accessing the field via an interface.
func (v *AlarmMetricInput) GetDimensions() []AlarmMetricDimensionInput { return v.Dimensions }

// Register a cloud metric alarm with an instance. The alarm appears in the UI immediately and receives state transitions as soon as the cloud provider reports them. Webhooks from AWS CloudWatch, Azure Monitor, GCP Cloud Monitoring, and Prometheus Alertmanager match against `cloudResourceId` to attach state.
type CreateInstanceAlarmInput struct {
	// The cloud provider's unique identifier for the alarm. Used to correlate incoming state transition webhooks back to this alarm. Examples: a CloudWatch AlarmArn, a GCP alert policy name, an Azure alert id.
	CloudResourceId string `json:"cloudResourceId"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`). Optional for providers that don't expose this concept (e.g., Alertmanager, GCP).
	ComparisonOperator string `json:"comparisonOperator,omitempty"`
	// Human-readable name for the alarm. Shown in the UI and in notifications. Typically the alarm name registered with the cloud provider.
	DisplayName string `json:"displayName"`
	// The cloud metric this alarm evaluates. Optional; not all providers expose structured metric data.
	Metric *AlarmMetricInput `json:"metric,omitempty"`
	// Evaluation window in seconds over which the metric is aggregated before the comparison is applied. Optional.
	Period *int `json:"period,omitempty"`
	// The value crossed to trigger the alarm. Compared against the metric using `comparisonOperator`. Optional.
	Threshold *float64 `json:"threshold,omitempty"`
}

// GetCloudResourceId returns CreateInstanceAlarmInput.CloudResourceId, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetCloudResourceId() string { return v.CloudResourceId }

// GetComparisonOperator returns CreateInstanceAlarmInput.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetComparisonOperator() string { return v.ComparisonOperator }

// GetDisplayName returns CreateInstanceAlarmInput.DisplayName, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetDisplayName() string { return v.DisplayName }

// GetMetric returns CreateInstanceAlarmInput.Metric, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetMetric() *AlarmMetricInput { return v.Metric }

// GetPeriod returns CreateInstanceAlarmInput.Period, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetPeriod() *int { return v.Period }

// GetThreshold returns CreateInstanceAlarmInput.Threshold, and is useful for accessing the field via an interface.
func (v *CreateInstanceAlarmInput) GetThreshold() *float64 { return v.Threshold }

// Cursor-based pagination input for list queries.
//
// Use `limit` to control page size and `next`/`previous` cursors to navigate between
// pages. Cursors are opaque strings returned in the response's `cursor` field — pass
// them back exactly as received to fetch the adjacent page.
//
// ```graphql
// # First page (20 items by default)
// query { instances(organizationId: "my-org") { cursor { next } items { id } } }
//
// # Next page
// query { instances(organizationId: "my-org", cursor: { next: "eyJpZCI6..." }) { cursor { next } items { id } } }
//
// # Custom page size
// query { instances(organizationId: "my-org", cursor: { limit: 50 }) { cursor { next } items { id } } }
// ```
type Cursor struct {
	// Maximum number of items to return per page. Default: **20**. Minimum: **1**. Maximum: **100**.
	Limit int `json:"limit"`
	// Forward pagination cursor. Pass the `next` value from a previous response to fetch the next page. Mutually exclusive with `previous`.
	Next string `json:"next"`
	// Backward pagination cursor. Pass the `previous` value from a previous response to fetch the preceding page. Mutually exclusive with `next`.
	Previous string `json:"previous"`
}

// GetLimit returns Cursor.Limit, and is useful for accessing the field via an interface.
func (v *Cursor) GetLimit() int { return v.Limit }

// GetNext returns Cursor.Next, and is useful for accessing the field via an interface.
func (v *Cursor) GetNext() string { return v.Next }

// GetPrevious returns Cursor.Previous, and is useful for accessing the field via an interface.
func (v *Cursor) GetPrevious() string { return v.Previous }

// Filter by an identifier field.
//
// All operators within a single filter are combined with **AND**. To match any of
// several values, use the `in` operator rather than multiple `eq` filters.
//
// ```graphql
// # Exact match
// { "id": { "eq": "my-resource" } }
//
// # Match several IDs (logical OR between values)
// { "id": { "in": ["resource-a", "resource-b"] } }
// ```
type IdFilter struct {
	// Return only results whose ID exactly equals this value.
	Eq string `json:"eq,omitempty"`
	// Return results whose ID matches any value in this list.
	In []string `json:"in,omitempty"`
}

// GetEq returns IdFilter.Eq, and is useful for accessing the field via an interface.
func (v *IdFilter) GetEq() string { return v.Eq }

// GetIn returns IdFilter.In, and is useful for accessing the field via an interface.
func (v *IdFilter) GetIn() []string { return v.In }

// Narrows the instance alarms list to only matching records.
//
// All filters are combined with AND logic. Omit a filter to skip that criterion.
type InstanceAlarmsFilter struct {
	// Return only alarms in the specified project(s).
	ProjectId *IdFilter `json:"projectId,omitempty"`
	// Return only alarms in the specified environment(s).
	EnvironmentId *IdFilter `json:"environmentId,omitempty"`
	// Return only alarms attached to the specified component(s).
	ComponentId *IdFilter `json:"componentId,omitempty"`
	// Return only alarms for the specified instance(s).
	InstanceId *IdFilter `json:"instanceId,omitempty"`
	// Return only alarms on instances of the given bundle (e.g., `aws-rds`).
	OciRepoName *OciRepoNameFilter `json:"ociRepoName,omitempty"`
}

// GetProjectId returns InstanceAlarmsFilter.ProjectId, and is useful for accessing the field via an interface.
func (v *InstanceAlarmsFilter) GetProjectId() *IdFilter { return v.ProjectId }

// GetEnvironmentId returns InstanceAlarmsFilter.EnvironmentId, and is useful for accessing the field via an interface.
func (v *InstanceAlarmsFilter) GetEnvironmentId() *IdFilter { return v.EnvironmentId }

// GetComponentId returns InstanceAlarmsFilter.ComponentId, and is useful for accessing the field via an interface.
func (v *InstanceAlarmsFilter) GetComponentId() *IdFilter { return v.ComponentId }

// GetInstanceId returns InstanceAlarmsFilter.InstanceId, and is useful for accessing the field via an interface.
func (v *InstanceAlarmsFilter) GetInstanceId() *IdFilter { return v.InstanceId }

// GetOciRepoName returns InstanceAlarmsFilter.OciRepoName, and is useful for accessing the field via an interface.
func (v *InstanceAlarmsFilter) GetOciRepoName() *OciRepoNameFilter { return v.OciRepoName }

// Filter by OCI repository name (the bundle's package identifier).
//
// Supports exact match, set membership, and prefix matching. Prefix matching is
// useful for filtering by cloud provider (e.g., `"aws-"`) or category.
//
// ```graphql
// # All AWS bundles
// { "ociRepoName": { "startsWith": "aws-" } }
//
// # Specific bundles
// { "ociRepoName": { "in": ["aws-aurora-postgres", "gcp-cloud-sql"] } }
// ```
type OciRepoNameFilter struct {
	// Return only results whose OCI repository name exactly equals this value.
	Eq string `json:"eq,omitempty"`
	// Return results whose OCI repository name matches any value in this list.
	In []string `json:"in,omitempty"`
	// Return results whose OCI repository name begins with this prefix, e.g. `"aws-"` matches `"aws-aurora-postgres"`.
	StartsWith string `json:"startsWith,omitempty"`
}

// GetEq returns OciRepoNameFilter.Eq, and is useful for accessing the field via an interface.
func (v *OciRepoNameFilter) GetEq() string { return v.Eq }

// GetIn returns OciRepoNameFilter.In, and is useful for accessing the field via an interface.
func (v *OciRepoNameFilter) GetIn() []string { return v.In }

// GetStartsWith returns OciRepoNameFilter.StartsWith, and is useful for accessing the field via an interface.
func (v *OciRepoNameFilter) GetStartsWith() string { return v.StartsWith }

// Update a registered alarm's mutable fields. Omit a field to leave it unchanged.
type UpdateInstanceAlarmInput struct {
	// The cloud provider's unique identifier for the alarm. Updating this changes which incoming webhooks correlate to this alarm.
	CloudResourceId string `json:"cloudResourceId,omitempty"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`).
	ComparisonOperator string `json:"comparisonOperator,omitempty"`
	// Human-readable name for the alarm. Shown in the UI and in notifications.
	DisplayName string `json:"displayName,omitempty"`
	// The cloud metric this alarm evaluates.
	Metric *AlarmMetricInput `json:"metric,omitempty"`
	// Evaluation window in seconds over which the metric is aggregated.
	Period *int `json:"period,omitempty"`
	// The value crossed to trigger the alarm.
	Threshold *float64 `json:"threshold,omitempty"`
}

// GetCloudResourceId returns UpdateInstanceAlarmInput.CloudResourceId, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetCloudResourceId() string { return v.CloudResourceId }

// GetComparisonOperator returns UpdateInstanceAlarmInput.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetComparisonOperator() string { return v.ComparisonOperator }

// GetDisplayName returns UpdateInstanceAlarmInput.DisplayName, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetDisplayName() string { return v.DisplayName }

// GetMetric returns UpdateInstanceAlarmInput.Metric, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetMetric() *AlarmMetricInput { return v.Metric }

// GetPeriod returns UpdateInstanceAlarmInput.Period, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetPeriod() *int { return v.Period }

// GetThreshold returns UpdateInstanceAlarmInput.Threshold, and is useful for accessing the field via an interface.
func (v *UpdateInstanceAlarmInput) GetThreshold() *float64 { return v.Threshold }

// __createInstanceAlarmInput is used internally by genqlient
type __createInstanceAlarmInput struct {
	OrganizationId string                   `json:"organizationId"`
	InstanceId     string                   `json:"instanceId"`
	Input          CreateInstanceAlarmInput `json:"input"`
}

// GetOrganizationId returns __createInstanceAlarmInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__createInstanceAlarmInput) GetOrganizationId() string { return v.OrganizationId }

// GetInstanceId returns __createInstanceAlarmInput.InstanceId, and is useful for accessing the field via an interface.
func (v *__createInstanceAlarmInput) GetInstanceId() string { return v.InstanceId }

// GetInput returns __createInstanceAlarmInput.Input, and is useful for accessing the field via an interface.
func (v *__createInstanceAlarmInput) GetInput() CreateInstanceAlarmInput { return v.Input }

// __deleteInstanceAlarmInput is used internally by genqlient
type __deleteInstanceAlarmInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __deleteInstanceAlarmInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__deleteInstanceAlarmInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __deleteInstanceAlarmInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteInstanceAlarmInput) GetId() string { return v.Id }

// __getInstanceAlarmInput is used internally by genqlient
type __getInstanceAlarmInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __getInstanceAlarmInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getInstanceAlarmInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __getInstanceAlarmInput.Id, and is useful for accessing the field via an interface.
func (v *__getInstanceAlarmInput) GetId() string { return v.Id }

// __listInstanceAlarmsInput is used internally by genqlient
type __listInstanceAlarmsInput struct {
	OrganizationId string                `json:"organizationId"`
	Filter         *InstanceAlarmsFilter `json:"filter,omitempty"`
	Cursor         *Cursor               `json:"cursor,omitempty"`
}

// GetOrganizationId returns __listInstanceAlarmsInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__listInstanceAlarmsInput) GetOrganizationId() string { return v.OrganizationId }

// GetFilter returns __listInstanceAlarmsInput.Filter, and is useful for accessing the field via an interface.
func (v *__listInstanceAlarmsInput) GetFilter() *InstanceAlarmsFilter { return v.Filter }

// GetCursor returns __listInstanceAlarmsInput.Cursor, and is useful for accessing the field via an interface.
func (v *__listInstanceAlarmsInput) GetCursor() *Cursor { return v.Cursor }

// __updateInstanceAlarmInput is used internally by genqlient
type __updateInstanceAlarmInput struct {
	OrganizationId string                   `json:"organizationId"`
	Id             string                   `json:"id"`
	Input          UpdateInstanceAlarmInput `json:"input"`
}

// GetOrganizationId returns __updateInstanceAlarmInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__updateInstanceAlarmInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __updateInstanceAlarmInput.Id, and is useful for accessing the field via an interface.
func (v *__updateInstanceAlarmInput) GetId() string { return v.Id }

// GetInput returns __updateInstanceAlarmInput.Input, and is useful for accessing the field via an interface.
func (v *__updateInstanceAlarmInput) GetInput() UpdateInstanceAlarmInput { return v.Input }

// createInstanceAlarmCreateInstanceAlarmAlarmPayload includes the requested fields of the GraphQL type AlarmPayload.
type createInstanceAlarmCreateInstanceAlarmAlarmPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage `json:"messages"`
}

// GetResult returns createInstanceAlarmCreateInstanceAlarmAlarmPayload.Result, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayload) GetResult() createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm {
	return v.Result
}

// GetSuccessful returns createInstanceAlarmCreateInstanceAlarmAlarmPayload.Successful, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns createInstanceAlarmCreateInstanceAlarmAlarmPayload.Messages, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayload) GetMessages() []createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage {
	return v.Messages
}

// createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage struct {
	// A unique error code for the type of validation used.
	Code string `json:"code"`
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
}

// GetCode returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// GetField returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm includes the requested fields of the GraphQL type Alarm.
// The GraphQL type's documentation follows.
//
// A cloud metric alarm attached to an instance.
//
// Receives state updates via webhooks from AWS CloudWatch, Azure Monitor,
// GCP Cloud Monitoring, or Prometheus Alertmanager.
//
// Check `currentState` to see whether the alarm is firing. A `null`
// `currentState` means no state has been reported yet for this alarm.
type createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm struct {
	// Unique identifier for this alarm.
	Id string `json:"id"`
	// Human-readable name for the alarm, set by the cloud provider when the alarm was registered.
	DisplayName string `json:"displayName"`
	// The cloud provider's unique identifier for the alarm (e.g., CloudWatch AlarmArn, GCP alert policy name, Azure alert id).
	CloudResourceId string `json:"cloudResourceId"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`, `GREATER_THAN_OR_EQUAL_TO`, `LESS_THAN_OR_EQUAL_TO`). May be null for Alertmanager and GCP alarms.
	ComparisonOperator string `json:"comparisonOperator"`
	// The value crossed to trigger the alarm, compared using `comparisonOperator`. May be null for Alertmanager alarms and some GCP conditions.
	Threshold float64 `json:"threshold"`
	// Evaluation window in seconds over which the metric is aggregated before the comparison is applied. May be null for alarms ingested from providers that don't expose a period.
	Period int `json:"period"`
	// The cloud metric this alarm evaluates. May be null for alarms from providers that don't supply structured metric data (e.g., Alertmanager).
	Metric *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric `json:"metric"`
}

// GetId returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.Id, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetId() string { return v.Id }

// GetDisplayName returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.DisplayName, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetDisplayName() string {
	return v.DisplayName
}

// GetCloudResourceId returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.CloudResourceId, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetCloudResourceId() string {
	return v.CloudResourceId
}

// GetComparisonOperator returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetComparisonOperator() string {
	return v.ComparisonOperator
}

// GetThreshold returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.Threshold, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetThreshold() float64 {
	return v.Threshold
}

// GetPeriod returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.Period, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetPeriod() int {
	return v.Period
}

// GetMetric returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm.Metric, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarm) GetMetric() *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric {
	return v.Metric
}

// createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric includes the requested fields of the GraphQL type AlarmMetric.
// The GraphQL type's documentation follows.
//
// The cloud metric an alarm is evaluating.
//
// Shape and populated fields vary by provider. AWS and Azure populate
// `statistic` (e.g., `Average`, `Sum`, `Maximum`); GCP does not. `dimensions`
// are populated when the provider exposes them as structured key-value pairs.
type createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric struct {
	// Cloud service namespace that categorizes the metric. Examples: `AWS/RDS`, `Microsoft.Cache/Redis`, `cloudsql_database`.
	Namespace string `json:"namespace"`
	// Metric name within the namespace. Examples: `CPUUtilization` (AWS), `allpercentprocessortime` (Azure).
	Name string `json:"name"`
	// Aggregation function applied to metric samples. Examples: `Average`, `Sum`, `Maximum`. May be `null` for providers that don't use this concept (e.g., GCP).
	Statistic string `json:"statistic"`
	// Cloud region this metric is scoped to, when provider-reported.
	Region string `json:"region"`
	// Dimensions identifying the specific cloud resource being monitored. Empty list when the provider doesn't report structured dimensions.
	Dimensions []createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension `json:"dimensions"`
}

// GetNamespace returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric.Namespace, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric) GetNamespace() string {
	return v.Namespace
}

// GetName returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric.Name, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric) GetName() string {
	return v.Name
}

// GetStatistic returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric.Statistic, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric) GetStatistic() string {
	return v.Statistic
}

// GetRegion returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric.Region, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric) GetRegion() string {
	return v.Region
}

// GetDimensions returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric.Dimensions, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetric) GetDimensions() []createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension {
	return v.Dimensions
}

// createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension includes the requested fields of the GraphQL type AlarmMetricDimension.
// The GraphQL type's documentation follows.
//
// A key-value pair identifying the specific cloud resource a metric applies to.
//
// Examples: `{ name: "DBInstanceIdentifier", value: "db-abc123" }` for AWS RDS,
// `{ name: "InstanceId", value: "i-0a1b2c3d" }` for AWS EC2.
type createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension struct {
	// Dimension name as defined by the cloud provider.
	Name string `json:"name"`
	// Dimension value identifying the monitored resource.
	Value string `json:"value"`
}

// GetName returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension.Name, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension) GetName() string {
	return v.Name
}

// GetValue returns createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension.Value, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmCreateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension) GetValue() string {
	return v.Value
}

// createInstanceAlarmResponse is returned by createInstanceAlarm on success.
type createInstanceAlarmResponse struct {
	// Register a cloud metric alarm with an instance.
	//
	// The alarm appears in the UI immediately and starts receiving state updates
	// as soon as the cloud provider reports them. The `cloudResourceId` is used
	// to correlate inbound webhooks (CloudWatch, Azure Monitor, GCP Cloud
	// Monitoring, Alertmanager) back to this alarm — it must be unique within
	// the instance.
	//
	// Requires `environment:update` on the alarm's environment.
	CreateInstanceAlarm createInstanceAlarmCreateInstanceAlarmAlarmPayload `json:"createInstanceAlarm"`
}

// GetCreateInstanceAlarm returns createInstanceAlarmResponse.CreateInstanceAlarm, and is useful for accessing the field via an interface.
func (v *createInstanceAlarmResponse) GetCreateInstanceAlarm() createInstanceAlarmCreateInstanceAlarmAlarmPayload {
	return v.CreateInstanceAlarm
}

// deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload includes the requested fields of the GraphQL type AlarmPayload.
type deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage `json:"messages"`
}

// GetResult returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload.Result, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload) GetResult() deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm {
	return v.Result
}

// GetSuccessful returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload.Successful, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload.Messages, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload) GetMessages() []deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage {
	return v.Messages
}

// deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage struct {
	// A unique error code for the type of validation used.
	Code string `json:"code"`
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
}

// GetCode returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// GetField returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm includes the requested fields of the GraphQL type Alarm.
// The GraphQL type's documentation follows.
//
// A cloud metric alarm attached to an instance.
//
// Receives state updates via webhooks from AWS CloudWatch, Azure Monitor,
// GCP Cloud Monitoring, or Prometheus Alertmanager.
//
// Check `currentState` to see whether the alarm is firing. A `null`
// `currentState` means no state has been reported yet for this alarm.
type deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm struct {
	// Unique identifier for this alarm.
	Id string `json:"id"`
	// Human-readable name for the alarm, set by the cloud provider when the alarm was registered.
	DisplayName string `json:"displayName"`
}

// GetId returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm.Id, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm) GetId() string { return v.Id }

// GetDisplayName returns deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm.DisplayName, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmDeleteInstanceAlarmAlarmPayloadResultAlarm) GetDisplayName() string {
	return v.DisplayName
}

// deleteInstanceAlarmResponse is returned by deleteInstanceAlarm on success.
type deleteInstanceAlarmResponse struct {
	// Delete an alarm registration.
	//
	// Removes the alarm and any recorded state transitions. The underlying cloud
	// provider alarm is unaffected.
	//
	// Requires `environment:update` on the alarm's environment.
	DeleteInstanceAlarm deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload `json:"deleteInstanceAlarm"`
}

// GetDeleteInstanceAlarm returns deleteInstanceAlarmResponse.DeleteInstanceAlarm, and is useful for accessing the field via an interface.
func (v *deleteInstanceAlarmResponse) GetDeleteInstanceAlarm() deleteInstanceAlarmDeleteInstanceAlarmAlarmPayload {
	return v.DeleteInstanceAlarm
}

// getInstanceAlarmInstanceAlarm includes the requested fields of the GraphQL type Alarm.
// The GraphQL type's documentation follows.
//
// A cloud metric alarm attached to an instance.
//
// Receives state updates via webhooks from AWS CloudWatch, Azure Monitor,
// GCP Cloud Monitoring, or Prometheus Alertmanager.
//
// Check `currentState` to see whether the alarm is firing. A `null`
// `currentState` means no state has been reported yet for this alarm.
type getInstanceAlarmInstanceAlarm struct {
	// Unique identifier for this alarm.
	Id string `json:"id"`
	// Human-readable name for the alarm, set by the cloud provider when the alarm was registered.
	DisplayName string `json:"displayName"`
	// The cloud provider's unique identifier for the alarm (e.g., CloudWatch AlarmArn, GCP alert policy name, Azure alert id).
	CloudResourceId string `json:"cloudResourceId"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`, `GREATER_THAN_OR_EQUAL_TO`, `LESS_THAN_OR_EQUAL_TO`). May be null for Alertmanager and GCP alarms.
	ComparisonOperator string `json:"comparisonOperator"`
	// The value crossed to trigger the alarm, compared using `comparisonOperator`. May be null for Alertmanager alarms and some GCP conditions.
	Threshold float64 `json:"threshold"`
	// Evaluation window in seconds over which the metric is aggregated before the comparison is applied. May be null for alarms ingested from providers that don't expose a period.
	Period int `json:"period"`
	// The cloud metric this alarm evaluates. May be null for alarms from providers that don't supply structured metric data (e.g., Alertmanager).
	Metric *getInstanceAlarmInstanceAlarmMetric `json:"metric"`
}

// GetId returns getInstanceAlarmInstanceAlarm.Id, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetId() string { return v.Id }

// GetDisplayName returns getInstanceAlarmInstanceAlarm.DisplayName, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetDisplayName() string { return v.DisplayName }

// GetCloudResourceId returns getInstanceAlarmInstanceAlarm.CloudResourceId, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetCloudResourceId() string { return v.CloudResourceId }

// GetComparisonOperator returns getInstanceAlarmInstanceAlarm.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetComparisonOperator() string { return v.ComparisonOperator }

// GetThreshold returns getInstanceAlarmInstanceAlarm.Threshold, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetThreshold() float64 { return v.Threshold }

// GetPeriod returns getInstanceAlarmInstanceAlarm.Period, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetPeriod() int { return v.Period }

// GetMetric returns getInstanceAlarmInstanceAlarm.Metric, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarm) GetMetric() *getInstanceAlarmInstanceAlarmMetric {
	return v.Metric
}

// getInstanceAlarmInstanceAlarmMetric includes the requested fields of the GraphQL type AlarmMetric.
// The GraphQL type's documentation follows.
//
// The cloud metric an alarm is evaluating.
//
// Shape and populated fields vary by provider. AWS and Azure populate
// `statistic` (e.g., `Average`, `Sum`, `Maximum`); GCP does not. `dimensions`
// are populated when the provider exposes them as structured key-value pairs.
type getInstanceAlarmInstanceAlarmMetric struct {
	// Cloud service namespace that categorizes the metric. Examples: `AWS/RDS`, `Microsoft.Cache/Redis`, `cloudsql_database`.
	Namespace string `json:"namespace"`
	// Metric name within the namespace. Examples: `CPUUtilization` (AWS), `allpercentprocessortime` (Azure).
	Name string `json:"name"`
	// Aggregation function applied to metric samples. Examples: `Average`, `Sum`, `Maximum`. May be `null` for providers that don't use this concept (e.g., GCP).
	Statistic string `json:"statistic"`
	// Cloud region this metric is scoped to, when provider-reported.
	Region string `json:"region"`
	// Dimensions identifying the specific cloud resource being monitored. Empty list when the provider doesn't report structured dimensions.
	Dimensions []getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension `json:"dimensions"`
}

// GetNamespace returns getInstanceAlarmInstanceAlarmMetric.Namespace, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetric) GetNamespace() string { return v.Namespace }

// GetName returns getInstanceAlarmInstanceAlarmMetric.Name, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetric) GetName() string { return v.Name }

// GetStatistic returns getInstanceAlarmInstanceAlarmMetric.Statistic, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetric) GetStatistic() string { return v.Statistic }

// GetRegion returns getInstanceAlarmInstanceAlarmMetric.Region, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetric) GetRegion() string { return v.Region }

// GetDimensions returns getInstanceAlarmInstanceAlarmMetric.Dimensions, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetric) GetDimensions() []getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension {
	return v.Dimensions
}

// getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension includes the requested fields of the GraphQL type AlarmMetricDimension.
// The GraphQL type's documentation follows.
//
// A key-value pair identifying the specific cloud resource a metric applies to.
//
// Examples: `{ name: "DBInstanceIdentifier", value: "db-abc123" }` for AWS RDS,
// `{ name: "InstanceId", value: "i-0a1b2c3d" }` for AWS EC2.
type getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension struct {
	// Dimension name as defined by the cloud provider.
	Name string `json:"name"`
	// Dimension value identifying the monitored resource.
	Value string `json:"value"`
}

// GetName returns getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension.Name, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension) GetName() string {
	return v.Name
}

// GetValue returns getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension.Value, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmInstanceAlarmMetricDimensionsAlarmMetricDimension) GetValue() string {
	return v.Value
}

// getInstanceAlarmResponse is returned by getInstanceAlarm on success.
type getInstanceAlarmResponse struct {
	// Fetch a single alarm by its unique identifier.
	//
	// Returns the alarm with its most recent `currentState` attached, or a
	// `NOT_FOUND` error if the alarm doesn't exist or its project isn't
	// visible to the caller.
	//
	// ```graphql
	// query {
	// instanceAlarm(organizationId: "my-org", id: "0192…uuid") {
	// id
	// displayName
	// currentState { status occurredAt }
	// metric { namespace name }
	// }
	// }
	// ```
	InstanceAlarm getInstanceAlarmInstanceAlarm `json:"instanceAlarm"`
}

// GetInstanceAlarm returns getInstanceAlarmResponse.InstanceAlarm, and is useful for accessing the field via an interface.
func (v *getInstanceAlarmResponse) GetInstanceAlarm() getInstanceAlarmInstanceAlarm {
	return v.InstanceAlarm
}

// listInstanceAlarmsInstanceAlarmsAlarmsPage includes the requested fields of the GraphQL type AlarmsPage.
type listInstanceAlarmsInstanceAlarmsAlarmsPage struct {
	// Pagination cursors for navigating between pages.
	Cursor listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor `json:"cursor"`
	// A list of type alarm.
	Items []listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm `json:"items"`
}

// GetCursor returns listInstanceAlarmsInstanceAlarmsAlarmsPage.Cursor, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPage) GetCursor() listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor {
	return v.Cursor
}

// GetItems returns listInstanceAlarmsInstanceAlarmsAlarmsPage.Items, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPage) GetItems() []listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm {
	return v.Items
}

// listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor includes the requested fields of the GraphQL type PaginationCursor.
// The GraphQL type's documentation follows.
//
// Pagination cursors returned with every paginated response.
//
// Contains opaque cursor strings for navigating forward and backward through results.
// A `null` value for `next` indicates you have reached the last page; a `null` value
// for `previous` indicates you are on the first page.
type listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor struct {
	// Cursor for the next page. `null` if there are no more results.
	Next string `json:"next"`
}

// GetNext returns listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor.Next, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageCursorPaginationCursor) GetNext() string {
	return v.Next
}

// listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm includes the requested fields of the GraphQL type Alarm.
// The GraphQL type's documentation follows.
//
// A cloud metric alarm attached to an instance.
//
// Receives state updates via webhooks from AWS CloudWatch, Azure Monitor,
// GCP Cloud Monitoring, or Prometheus Alertmanager.
//
// Check `currentState` to see whether the alarm is firing. A `null`
// `currentState` means no state has been reported yet for this alarm.
type listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm struct {
	// Unique identifier for this alarm.
	Id string `json:"id"`
	// Human-readable name for the alarm, set by the cloud provider when the alarm was registered.
	DisplayName string `json:"displayName"`
	// The cloud provider's unique identifier for the alarm (e.g., CloudWatch AlarmArn, GCP alert policy name, Azure alert id).
	CloudResourceId string `json:"cloudResourceId"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`, `GREATER_THAN_OR_EQUAL_TO`, `LESS_THAN_OR_EQUAL_TO`). May be null for Alertmanager and GCP alarms.
	ComparisonOperator string `json:"comparisonOperator"`
	// The value crossed to trigger the alarm, compared using `comparisonOperator`. May be null for Alertmanager alarms and some GCP conditions.
	Threshold float64 `json:"threshold"`
	// Evaluation window in seconds over which the metric is aggregated before the comparison is applied. May be null for alarms ingested from providers that don't expose a period.
	Period int `json:"period"`
	// The cloud metric this alarm evaluates. May be null for alarms from providers that don't supply structured metric data (e.g., Alertmanager).
	Metric *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric `json:"metric"`
}

// GetId returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.Id, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetId() string { return v.Id }

// GetDisplayName returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.DisplayName, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetDisplayName() string {
	return v.DisplayName
}

// GetCloudResourceId returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.CloudResourceId, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetCloudResourceId() string {
	return v.CloudResourceId
}

// GetComparisonOperator returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetComparisonOperator() string {
	return v.ComparisonOperator
}

// GetThreshold returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.Threshold, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetThreshold() float64 {
	return v.Threshold
}

// GetPeriod returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.Period, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetPeriod() int { return v.Period }

// GetMetric returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm.Metric, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarm) GetMetric() *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric {
	return v.Metric
}

// listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric includes the requested fields of the GraphQL type AlarmMetric.
// The GraphQL type's documentation follows.
//
// The cloud metric an alarm is evaluating.
//
// Shape and populated fields vary by provider. AWS and Azure populate
// `statistic` (e.g., `Average`, `Sum`, `Maximum`); GCP does not. `dimensions`
// are populated when the provider exposes them as structured key-value pairs.
type listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric struct {
	// Cloud service namespace that categorizes the metric. Examples: `AWS/RDS`, `Microsoft.Cache/Redis`, `cloudsql_database`.
	Namespace string `json:"namespace"`
	// Metric name within the namespace. Examples: `CPUUtilization` (AWS), `allpercentprocessortime` (Azure).
	Name string `json:"name"`
	// Aggregation function applied to metric samples. Examples: `Average`, `Sum`, `Maximum`. May be `null` for providers that don't use this concept (e.g., GCP).
	Statistic string `json:"statistic"`
	// Cloud region this metric is scoped to, when provider-reported.
	Region string `json:"region"`
	// Dimensions identifying the specific cloud resource being monitored. Empty list when the provider doesn't report structured dimensions.
	Dimensions []listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension `json:"dimensions"`
}

// GetNamespace returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric.Namespace, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric) GetNamespace() string {
	return v.Namespace
}

// GetName returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric.Name, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric) GetName() string { return v.Name }

// GetStatistic returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric.Statistic, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric) GetStatistic() string {
	return v.Statistic
}

// GetRegion returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric.Region, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric) GetRegion() string {
	return v.Region
}

// GetDimensions returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric.Dimensions, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetric) GetDimensions() []listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension {
	return v.Dimensions
}

// listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension includes the requested fields of the GraphQL type AlarmMetricDimension.
// The GraphQL type's documentation follows.
//
// A key-value pair identifying the specific cloud resource a metric applies to.
//
// Examples: `{ name: "DBInstanceIdentifier", value: "db-abc123" }` for AWS RDS,
// `{ name: "InstanceId", value: "i-0a1b2c3d" }` for AWS EC2.
type listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension struct {
	// Dimension name as defined by the cloud provider.
	Name string `json:"name"`
	// Dimension value identifying the monitored resource.
	Value string `json:"value"`
}

// GetName returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension.Name, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension) GetName() string {
	return v.Name
}

// GetValue returns listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension.Value, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsInstanceAlarmsAlarmsPageItemsAlarmMetricDimensionsAlarmMetricDimension) GetValue() string {
	return v.Value
}

// listInstanceAlarmsResponse is returned by listInstanceAlarms on success.
type listInstanceAlarmsResponse struct {
	// List alarms across all projects you can see.
	//
	// Returns a paginated list. Use `filter` to narrow by project, environment,
	// component, bundle (`ociRepoName`), or instance. Default sort is
	// alphabetical by `displayName`.
	//
	// ```graphql
	// query {
	// instanceAlarms(
	// organizationId: "my-org"
	// filter: { environmentId: { eq: "prod" }, ociRepoName: { eq: "aws-rds" } }
	// ) {
	// items { id displayName currentState { status occurredAt } }
	// cursor { next }
	// }
	// }
	// ```
	InstanceAlarms listInstanceAlarmsInstanceAlarmsAlarmsPage `json:"instanceAlarms"`
}

// GetInstanceAlarms returns listInstanceAlarmsResponse.InstanceAlarms, and is useful for accessing the field via an interface.
func (v *listInstanceAlarmsResponse) GetInstanceAlarms() listInstanceAlarmsInstanceAlarmsAlarmsPage {
	return v.InstanceAlarms
}

// updateInstanceAlarmResponse is returned by updateInstanceAlarm on success.
type updateInstanceAlarmResponse struct {
	// Update a registered alarm's mutable fields.
	//
	// Omit a field from the input to leave it unchanged.
	//
	// Requires `environment:update` on the alarm's environment.
	UpdateInstanceAlarm updateInstanceAlarmUpdateInstanceAlarmAlarmPayload `json:"updateInstanceAlarm"`
}

// GetUpdateInstanceAlarm returns updateInstanceAlarmResponse.UpdateInstanceAlarm, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmResponse) GetUpdateInstanceAlarm() updateInstanceAlarmUpdateInstanceAlarmAlarmPayload {
	return v.UpdateInstanceAlarm
}

// updateInstanceAlarmUpdateInstanceAlarmAlarmPayload includes the requested fields of the GraphQL type AlarmPayload.
type updateInstanceAlarmUpdateInstanceAlarmAlarmPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage `json:"messages"`
}

// GetResult returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayload.Result, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayload) GetResult() updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm {
	return v.Result
}

// GetSuccessful returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayload.Successful, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayload.Messages, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayload) GetMessages() []updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage {
	return v.Messages
}

// updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage struct {
	// A unique error code for the type of validation used.
	Code string `json:"code"`
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
}

// GetCode returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// GetField returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm includes the requested fields of the GraphQL type Alarm.
// The GraphQL type's documentation follows.
//
// A cloud metric alarm attached to an instance.
//
// Receives state updates via webhooks from AWS CloudWatch, Azure Monitor,
// GCP Cloud Monitoring, or Prometheus Alertmanager.
//
// Check `currentState` to see whether the alarm is firing. A `null`
// `currentState` means no state has been reported yet for this alarm.
type updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm struct {
	// Unique identifier for this alarm.
	Id string `json:"id"`
	// Human-readable name for the alarm, set by the cloud provider when the alarm was registered.
	DisplayName string `json:"displayName"`
	// The cloud provider's unique identifier for the alarm (e.g., CloudWatch AlarmArn, GCP alert policy name, Azure alert id).
	CloudResourceId string `json:"cloudResourceId"`
	// How the metric is compared against `threshold` (e.g., `GREATER_THAN`, `LESS_THAN`, `GREATER_THAN_OR_EQUAL_TO`, `LESS_THAN_OR_EQUAL_TO`). May be null for Alertmanager and GCP alarms.
	ComparisonOperator string `json:"comparisonOperator"`
	// The value crossed to trigger the alarm, compared using `comparisonOperator`. May be null for Alertmanager alarms and some GCP conditions.
	Threshold float64 `json:"threshold"`
	// Evaluation window in seconds over which the metric is aggregated before the comparison is applied. May be null for alarms ingested from providers that don't expose a period.
	Period int `json:"period"`
	// The cloud metric this alarm evaluates. May be null for alarms from providers that don't supply structured metric data (e.g., Alertmanager).
	Metric *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric `json:"metric"`
}

// GetId returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.Id, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetId() string { return v.Id }

// GetDisplayName returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.DisplayName, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetDisplayName() string {
	return v.DisplayName
}

// GetCloudResourceId returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.CloudResourceId, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetCloudResourceId() string {
	return v.CloudResourceId
}

// GetComparisonOperator returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.ComparisonOperator, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetComparisonOperator() string {
	return v.ComparisonOperator
}

// GetThreshold returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.Threshold, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetThreshold() float64 {
	return v.Threshold
}

// GetPeriod returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.Period, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetPeriod() int {
	return v.Period
}

// GetMetric returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm.Metric, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarm) GetMetric() *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric {
	return v.Metric
}

// updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric includes the requested fields of the GraphQL type AlarmMetric.
// The GraphQL type's documentation follows.
//
// The cloud metric an alarm is evaluating.
//
// Shape and populated fields vary by provider. AWS and Azure populate
// `statistic` (e.g., `Average`, `Sum`, `Maximum`); GCP does not. `dimensions`
// are populated when the provider exposes them as structured key-value pairs.
type updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric struct {
	// Cloud service namespace that categorizes the metric. Examples: `AWS/RDS`, `Microsoft.Cache/Redis`, `cloudsql_database`.
	Namespace string `json:"namespace"`
	// Metric name within the namespace. Examples: `CPUUtilization` (AWS), `allpercentprocessortime` (Azure).
	Name string `json:"name"`
	// Aggregation function applied to metric samples. Examples: `Average`, `Sum`, `Maximum`. May be `null` for providers that don't use this concept (e.g., GCP).
	Statistic string `json:"statistic"`
	// Cloud region this metric is scoped to, when provider-reported.
	Region string `json:"region"`
	// Dimensions identifying the specific cloud resource being monitored. Empty list when the provider doesn't report structured dimensions.
	Dimensions []updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension `json:"dimensions"`
}

// GetNamespace returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric.Namespace, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric) GetNamespace() string {
	return v.Namespace
}

// GetName returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric.Name, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric) GetName() string {
	return v.Name
}

// GetStatistic returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric.Statistic, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric) GetStatistic() string {
	return v.Statistic
}

// GetRegion returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric.Region, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric) GetRegion() string {
	return v.Region
}

// GetDimensions returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric.Dimensions, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetric) GetDimensions() []updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension {
	return v.Dimensions
}

// updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension includes the requested fields of the GraphQL type AlarmMetricDimension.
// The GraphQL type's documentation follows.
//
// A key-value pair identifying the specific cloud resource a metric applies to.
//
// Examples: `{ name: "DBInstanceIdentifier", value: "db-abc123" }` for AWS RDS,
// `{ name: "InstanceId", value: "i-0a1b2c3d" }` for AWS EC2.
type updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension struct {
	// Dimension name as defined by the cloud provider.
	Name string `json:"name"`
	// Dimension value identifying the monitored resource.
	Value string `json:"value"`
}

// GetName returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension.Name, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension) GetName() string {
	return v.Name
}

// GetValue returns updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension.Value, and is useful for accessing the field via an interface.
func (v *updateInstanceAlarmUpdateInstanceAlarmAlarmPayloadResultAlarmMetricDimensionsAlarmMetricDimension) GetValue() string {
	return v.Value
}

// The mutation executed by createInstanceAlarm.
const createInstanceAlarm_Operation = `
mutation createInstanceAlarm ($organizationId: ID!, $instanceId: ID!, $input: CreateInstanceAlarmInput!) {
	createInstanceAlarm(organizationId: $organizationId, instanceId: $instanceId, input: $input) {
		result {
			id
			displayName
			cloudResourceId
			comparisonOperator
			threshold
			period
			metric {
				namespace
				name
				statistic
				region
				dimensions {
					name
					value
				}
			}
		}
		successful
		messages {
			code
			field
			message
		}
	}
}
`

func createInstanceAlarm(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	instanceId string,
	input CreateInstanceAlarmInput,
) (data_ *createInstanceAlarmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createInstanceAlarm",
		Query:  createInstanceAlarm_Operation,
		Variables: &__createInstanceAlarmInput{
			OrganizationId: organizationId,
			InstanceId:     instanceId,
			Input:          input,
		},
	}

	data_ = &createInstanceAlarmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteInstanceAlarm.
const deleteInstanceAlarm_Operation = `
mutation deleteInstanceAlarm ($organizationId: ID!, $id: UUID!) {
	deleteInstanceAlarm(organizationId: $organizationId, id: $id) {
		result {
			id
			displayName
		}
		successful
		messages {
			code
			field
			message
		}
	}
}
`

func deleteInstanceAlarm(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	id string,
) (data_ *deleteInstanceAlarmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteInstanceAlarm",
		Query:  deleteInstanceAlarm_Operation,
		Variables: &__deleteInstanceAlarmInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}

	data_ = &deleteInstanceAlarmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getInstanceAlarm.
const getInstanceAlarm_Operation = `
query getInstanceAlarm ($organizationId: ID!, $id: UUID!) {
	instanceAlarm(organizationId: $organizationId, id: $id) {
		id
		displayName
		cloudResourceId
		comparisonOperator
		threshold
		period
		metric {
			namespace
			name
			statistic
			region
			dimensions {
				name
				value
			}
		}
	}
}
`

func getInstanceAlarm(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	id string,
) (data_ *getInstanceAlarmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getInstanceAlarm",
		Query:  getInstanceAlarm_Operation,
		Variables: &__getInstanceAlarmInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}

	data_ = &getInstanceAlarmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listInstanceAlarms.
const listInstanceAlarms_Operation = `
query listInstanceAlarms ($organizationId: ID!, $filter: InstanceAlarmsFilter, $cursor: Cursor) {
	instanceAlarms(organizationId: $organizationId, filter: $filter, cursor: $cursor) {
		cursor {
			next
		}
		items {
			id
			displayName
			cloudResourceId
			comparisonOperator
			threshold
			period
			metric {
				namespace
				name
				statistic
				region
				dimensions {
					name
					value
				}
			}
		}
	}
}
`

// listInstanceAlarms is used by the package_alarm self-heal path: when a user
// has lost the alarm's UUID from state (a pre-1.3 deploy with the dead REST
// endpoint silently cleared it), we can recover by listing alarms on the
// instance and matching by cloudResourceId client-side. The schema's filter
// doesn't expose cloudResourceId directly, so we filter by instanceId and
// walk the page items.
//
// Every InstanceAlarmsFilter field needs `omitempty: true, pointer: true` —
// otherwise unset fields marshal as bare empty objects (`"projectId": {}`),
// which the server interprets as a filter present-but-matching-nothing and
// silently returns zero items. The instance-only filter we want has to come
// across the wire as `{"instanceId": {"eq": "..."}}` with no sibling keys.
func listInstanceAlarms(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	filter *InstanceAlarmsFilter,
	cursor *Cursor,
) (data_ *listInstanceAlarmsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listInstanceAlarms",
		Query:  listInstanceAlarms_Operation,
		Variables: &__listInstanceAlarmsInput{
			OrganizationId: organizationId,
			Filter:         filter,
			Cursor:         cursor,
		},
	}

	data_ = &listInstanceAlarmsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by updateInstanceAlarm.
const updateInstanceAlarm_Operation = `
mutation updateInstanceAlarm ($organizationId: ID!, $id: UUID!, $input: UpdateInstanceAlarmInput!) {
	updateInstanceAlarm(organizationId: $organizationId, id: $id, input: $input) {
		result {
			id
			displayName
			cloudResourceId
			comparisonOperator
			threshold
			period
			metric {
				namespace
				name
				statistic
				region
				dimensions {
					name
					value
				}
			}
		}
		successful
		messages {
			code
			field
			message
		}
	}
}
`

func updateInstanceAlarm(
	ctx_ context.Context,
	client_ graphql.Client,
	organizationId string,
	id string,
	input UpdateInstanceAlarmInput,
) (data_ *updateInstanceAlarmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "updateInstanceAlarm",
		Query:  updateInstanceAlarm_Operation,
		Variables: &__updateInstanceAlarmInput{
			OrganizationId: organizationId,
			Id:             id,
			Input:          input,
		},
	}

	data_ = &updateInstanceAlarmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
