package projects

import (
	"context"
	"fmt"

	"github.com/Khan/genqlient/graphql"
	"github.com/massdriver-cloud/massdriver-sdk-go/massdriver/client"
)

type Service struct {
	client *client.Client
}

type Project struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func NewService(c *client.Client) *Service {
	return &Service{
		client: c,
	}
}

func (s *Service) CreateProject(ctx context.Context, project *Project) (*Project, error) {
	response, err := createProject(ctx, s.client.GQL, s.client.Config.OrganizationID, project.Name, project.Slug, project.Description)
	if err != nil {
		return nil, fmt.Errorf("failed to create project: %w", err)
	}

	if !response.CreateProject.Successful {
		messages := response.CreateProject.GetMessages()
		if len(messages) > 0 {
			errMsg := "unable to create project:"
			for _, msg := range messages {
				errMsg += "\n  - " + msg.Message
			}
			return nil, fmt.Errorf("%s", errMsg)
		}
		return nil, fmt.Errorf("unable to create project")
	}

	result := response.CreateProject.Result
	return &Project{
		ID:          result.Id,
		Name:        result.Name,
		Slug:        result.Slug,
		Description: result.Description,
	}, nil
}

func (s *Service) GetProject(ctx context.Context, idOrSlug string) (*Project, error) {
	response, err := getProjectById(ctx, s.client.GQL, s.client.Config.OrganizationID, idOrSlug)
	if err != nil {
		return nil, fmt.Errorf("failed to get project: %w", err)
	}

	if response.Project.Id == "" {
		return nil, fmt.Errorf("not found")
	}

	return &Project{
		ID:          response.Project.Id,
		Name:        response.Project.Name,
		Slug:        response.Project.Slug,
		Description: response.Project.Description,
	}, nil
}

func (s *Service) UpdateProject(ctx context.Context, project *Project) (*Project, error) {
	response, err := updateProject(ctx, s.client.GQL, s.client.Config.OrganizationID, project.ID, project.Name, project.Description)
	if err != nil {
		return nil, fmt.Errorf("failed to update project: %w", err)
	}

	if !response.UpdateProject.Successful {
		messages := response.UpdateProject.GetMessages()
		if len(messages) > 0 {
			errMsg := "unable to update project:"
			for _, msg := range messages {
				errMsg += "\n  - " + msg.Message
			}
			return nil, fmt.Errorf("%s", errMsg)
		}
		return nil, fmt.Errorf("unable to update project")
	}

	result := response.UpdateProject.Result
	return &Project{
		ID:          result.Id,
		Name:        result.Name,
		Slug:        result.Slug,
		Description: result.Description,
	}, nil
}

func (s *Service) DeleteProject(ctx context.Context, idOrSlug string) error {
	response, err := deleteProject(ctx, s.client.GQL, s.client.Config.OrganizationID, idOrSlug)
	if err != nil {
		return fmt.Errorf("failed to delete project: %w", err)
	}

	if !response.DeleteProject.Successful {
		messages := response.DeleteProject.GetMessages()
		if len(messages) > 0 {
			errMsg := "unable to delete project:"
			for _, msg := range messages {
				errMsg += "\n  - " + msg.Message
			}
			return fmt.Errorf("%s", errMsg)
		}
		return fmt.Errorf("unable to delete project")
	}

	return nil
}

// GraphQL operations generated by genqlient

type createProjectResponse struct {
	CreateProject createProjectCreateProjectProjectPayload `json:"createProject"`
}

type createProjectCreateProjectProjectPayload struct {
	Result     createProjectCreateProjectProjectPayloadResult       `json:"result"`
	Successful bool                                                  `json:"successful"`
	Messages   []createProjectCreateProjectProjectPayloadMessages   `json:"messages"`
}

type createProjectCreateProjectProjectPayloadResult struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

type createProjectCreateProjectProjectPayloadMessages struct {
	Message string `json:"message"`
}

func (v *createProjectCreateProjectProjectPayload) GetMessages() []createProjectCreateProjectProjectPayloadMessages {
	if v != nil {
		return v.Messages
	}
	return nil
}

func createProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	name string,
	slug string,
	description string,
) (*createProjectResponse, error) {
	req := &graphql.Request{
		OpName: "createProject",
		Query: `
mutation createProject($organizationId: ID!, $name: String!, $slug: String!, $description: String) {
	createProject(organizationId: $organizationId, name: $name, slug: $slug, description: $description) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}`,
		Variables: map[string]interface{}{
			"organizationId": organizationId,
			"name":           name,
			"slug":           slug,
			"description":    description,
		},
	}

	var data createProjectResponse
	resp := &graphql.Response{Data: &data}

	err := client.MakeRequest(ctx, req, resp)
	return &data, err
}

type getProjectByIdResponse struct {
	Project getProjectByIdProject `json:"project"`
}

type getProjectByIdProject struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func getProjectById(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*getProjectByIdResponse, error) {
	req := &graphql.Request{
		OpName: "getProjectById",
		Query: `
query getProjectById($organizationId: ID!, $id: ID!) {
	project(organizationId: $organizationId, id: $id) {
		id
		name
		slug
		description
	}
}`,
		Variables: map[string]interface{}{
			"organizationId": organizationId,
			"id":             id,
		},
	}

	var data getProjectByIdResponse
	resp := &graphql.Response{Data: &data}

	err := client.MakeRequest(ctx, req, resp)
	return &data, err
}

type updateProjectResponse struct {
	UpdateProject updateProjectUpdateProjectProjectPayload `json:"updateProject"`
}

type updateProjectUpdateProjectProjectPayload struct {
	Result     updateProjectUpdateProjectProjectPayloadResult     `json:"result"`
	Successful bool                                                `json:"successful"`
	Messages   []updateProjectUpdateProjectProjectPayloadMessages `json:"messages"`
}

type updateProjectUpdateProjectProjectPayloadResult struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

type updateProjectUpdateProjectProjectPayloadMessages struct {
	Message string `json:"message"`
}

func (v *updateProjectUpdateProjectProjectPayload) GetMessages() []updateProjectUpdateProjectProjectPayloadMessages {
	if v != nil {
		return v.Messages
	}
	return nil
}

func updateProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
	name string,
	description string,
) (*updateProjectResponse, error) {
	req := &graphql.Request{
		OpName: "updateProject",
		Query: `
mutation updateProject($organizationId: ID!, $id: ID!, $name: String!, $description: String) {
	updateProject(organizationId: $organizationId, id: $id, name: $name, description: $description) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}`,
		Variables: map[string]interface{}{
			"organizationId": organizationId,
			"id":             id,
			"name":           name,
			"description":    description,
		},
	}

	var data updateProjectResponse
	resp := &graphql.Response{Data: &data}

	err := client.MakeRequest(ctx, req, resp)
	return &data, err
}

type deleteProjectResponse struct {
	DeleteProject deleteProjectDeleteProjectProjectPayload `json:"deleteProject"`
}

type deleteProjectDeleteProjectProjectPayload struct {
	Result     deleteProjectDeleteProjectProjectPayloadResult     `json:"result"`
	Successful bool                                                `json:"successful"`
	Messages   []deleteProjectDeleteProjectProjectPayloadMessages `json:"messages"`
}

type deleteProjectDeleteProjectProjectPayloadResult struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

type deleteProjectDeleteProjectProjectPayloadMessages struct {
	Message string `json:"message"`
}

func (v *deleteProjectDeleteProjectProjectPayload) GetMessages() []deleteProjectDeleteProjectProjectPayloadMessages {
	if v != nil {
		return v.Messages
	}
	return nil
}

func deleteProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*deleteProjectResponse, error) {
	req := &graphql.Request{
		OpName: "deleteProject",
		Query: `
mutation deleteProject($organizationId: ID!, $id: ID!) {
	deleteProject(organizationId: $organizationId, id: $id) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}`,
		Variables: map[string]interface{}{
			"organizationId": organizationId,
			"id":             id,
		},
	}

	var data deleteProjectResponse
	resp := &graphql.Response{Data: &data}

	err := client.MakeRequest(ctx, req, resp)
	return &data, err
}

