// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package massdriver

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// MutationValidationError includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type MutationValidationError struct {
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
}

// GetMessage returns MutationValidationError.Message, and is useful for accessing the field via an interface.
func (v *MutationValidationError) GetMessage() string { return v.Message }

// __createProjectInput is used internally by genqlient
type __createProjectInput struct {
	OrganizationId string `json:"organizationId"`
	Name           string `json:"name"`
	Slug           string `json:"slug"`
	Description    string `json:"description"`
}

// GetOrganizationId returns __createProjectInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetOrganizationId() string { return v.OrganizationId }

// GetName returns __createProjectInput.Name, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetName() string { return v.Name }

// GetSlug returns __createProjectInput.Slug, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetSlug() string { return v.Slug }

// GetDescription returns __createProjectInput.Description, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetDescription() string { return v.Description }

// __deleteProjectInput is used internally by genqlient
type __deleteProjectInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __deleteProjectInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __deleteProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetId() string { return v.Id }

// __getProjectByIdInput is used internally by genqlient
type __getProjectByIdInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
}

// GetOrganizationId returns __getProjectByIdInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__getProjectByIdInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __getProjectByIdInput.Id, and is useful for accessing the field via an interface.
func (v *__getProjectByIdInput) GetId() string { return v.Id }

// __updateProjectInput is used internally by genqlient
type __updateProjectInput struct {
	OrganizationId string `json:"organizationId"`
	Id             string `json:"id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
}

// GetOrganizationId returns __updateProjectInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetOrganizationId() string { return v.OrganizationId }

// GetId returns __updateProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetId() string { return v.Id }

// GetName returns __updateProjectInput.Name, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetName() string { return v.Name }

// GetDescription returns __updateProjectInput.Description, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetDescription() string { return v.Description }

// createProjectCreateProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type createProjectCreateProjectProjectPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result createProjectCreateProjectProjectPayloadResultProject `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns createProjectCreateProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetResult() createProjectCreateProjectProjectPayloadResultProject {
	return v.Result
}

// GetSuccessful returns createProjectCreateProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns createProjectCreateProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// createProjectCreateProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
type createProjectCreateProjectProjectPayloadResultProject struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// GetId returns createProjectCreateProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns createProjectCreateProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetName() string { return v.Name }

// GetSlug returns createProjectCreateProjectProjectPayloadResultProject.Slug, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetSlug() string { return v.Slug }

// GetDescription returns createProjectCreateProjectProjectPayloadResultProject.Description, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetDescription() string {
	return v.Description
}

// createProjectResponse is returned by createProject on success.
type createProjectResponse struct {
	// Create a project
	CreateProject createProjectCreateProjectProjectPayload `json:"createProject"`
}

// GetCreateProject returns createProjectResponse.CreateProject, and is useful for accessing the field via an interface.
func (v *createProjectResponse) GetCreateProject() createProjectCreateProjectProjectPayload {
	return v.CreateProject
}

// deleteProjectDeleteProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type deleteProjectDeleteProjectProjectPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deleteProjectDeleteProjectProjectPayloadResultProject `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns deleteProjectDeleteProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetResult() deleteProjectDeleteProjectProjectPayloadResultProject {
	return v.Result
}

// GetSuccessful returns deleteProjectDeleteProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns deleteProjectDeleteProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// deleteProjectDeleteProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
type deleteProjectDeleteProjectProjectPayloadResultProject struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// GetId returns deleteProjectDeleteProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns deleteProjectDeleteProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetName() string { return v.Name }

// GetSlug returns deleteProjectDeleteProjectProjectPayloadResultProject.Slug, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetSlug() string { return v.Slug }

// GetDescription returns deleteProjectDeleteProjectProjectPayloadResultProject.Description, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetDescription() string {
	return v.Description
}

// deleteProjectResponse is returned by deleteProject on success.
type deleteProjectResponse struct {
	DeleteProject deleteProjectDeleteProjectProjectPayload `json:"deleteProject"`
}

// GetDeleteProject returns deleteProjectResponse.DeleteProject, and is useful for accessing the field via an interface.
func (v *deleteProjectResponse) GetDeleteProject() deleteProjectDeleteProjectProjectPayload {
	return v.DeleteProject
}

// getProjectByIdProject includes the requested fields of the GraphQL type Project.
type getProjectByIdProject struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// GetId returns getProjectByIdProject.Id, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetId() string { return v.Id }

// GetName returns getProjectByIdProject.Name, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetName() string { return v.Name }

// GetSlug returns getProjectByIdProject.Slug, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetSlug() string { return v.Slug }

// GetDescription returns getProjectByIdProject.Description, and is useful for accessing the field via an interface.
func (v *getProjectByIdProject) GetDescription() string { return v.Description }

// getProjectByIdResponse is returned by getProjectById on success.
type getProjectByIdResponse struct {
	Project getProjectByIdProject `json:"project"`
}

// GetProject returns getProjectByIdResponse.Project, and is useful for accessing the field via an interface.
func (v *getProjectByIdResponse) GetProject() getProjectByIdProject { return v.Project }

// updateProjectResponse is returned by updateProject on success.
type updateProjectResponse struct {
	// Update a project
	UpdateProject updateProjectUpdateProjectProjectPayload `json:"updateProject"`
}

// GetUpdateProject returns updateProjectResponse.UpdateProject, and is useful for accessing the field via an interface.
func (v *updateProjectResponse) GetUpdateProject() updateProjectUpdateProjectProjectPayload {
	return v.UpdateProject
}

// updateProjectUpdateProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type updateProjectUpdateProjectProjectPayload struct {
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result updateProjectUpdateProjectProjectPayloadResultProject `json:"result"`
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []MutationValidationError `json:"messages"`
}

// GetResult returns updateProjectUpdateProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetResult() updateProjectUpdateProjectProjectPayloadResultProject {
	return v.Result
}

// GetSuccessful returns updateProjectUpdateProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns updateProjectUpdateProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetMessages() []MutationValidationError {
	return v.Messages
}

// updateProjectUpdateProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
type updateProjectUpdateProjectProjectPayloadResultProject struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// GetId returns updateProjectUpdateProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns updateProjectUpdateProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetName() string { return v.Name }

// GetSlug returns updateProjectUpdateProjectProjectPayloadResultProject.Slug, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetSlug() string { return v.Slug }

// GetDescription returns updateProjectUpdateProjectProjectPayloadResultProject.Description, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetDescription() string {
	return v.Description
}

// The query or mutation executed by createProject.
const createProject_Operation = `
mutation createProject ($organizationId: ID!, $name: String!, $slug: String!, $description: String) {
	createProject(organizationId: $organizationId, name: $name, slug: $slug, description: $description) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}
`

func createProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	name string,
	slug string,
	description string,
) (*createProjectResponse, error) {
	req := &graphql.Request{
		OpName: "createProject",
		Query:  createProject_Operation,
		Variables: &__createProjectInput{
			OrganizationId: organizationId,
			Name:           name,
			Slug:           slug,
			Description:    description,
		},
	}
	var err error

	var data createProjectResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by deleteProject.
const deleteProject_Operation = `
mutation deleteProject ($organizationId: ID!, $id: ID!) {
	deleteProject(organizationId: $organizationId, id: $id) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}
`

func deleteProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*deleteProjectResponse, error) {
	req := &graphql.Request{
		OpName: "deleteProject",
		Query:  deleteProject_Operation,
		Variables: &__deleteProjectInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}
	var err error

	var data deleteProjectResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getProjectById.
const getProjectById_Operation = `
query getProjectById ($organizationId: ID!, $id: ID!) {
	project(organizationId: $organizationId, id: $id) {
		id
		name
		slug
		description
	}
}
`

func getProjectById(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
) (*getProjectByIdResponse, error) {
	req := &graphql.Request{
		OpName: "getProjectById",
		Query:  getProjectById_Operation,
		Variables: &__getProjectByIdInput{
			OrganizationId: organizationId,
			Id:             id,
		},
	}
	var err error

	var data getProjectByIdResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by updateProject.
const updateProject_Operation = `
mutation updateProject ($organizationId: ID!, $id: ID!, $name: String!, $description: String) {
	updateProject(organizationId: $organizationId, id: $id, name: $name, description: $description) {
		result {
			id
			name
			slug
			description
		}
		successful
		messages {
			message
		}
	}
}
`

func updateProject(
	ctx context.Context,
	client graphql.Client,
	organizationId string,
	id string,
	name string,
	description string,
) (*updateProjectResponse, error) {
	req := &graphql.Request{
		OpName: "updateProject",
		Query:  updateProject_Operation,
		Variables: &__updateProjectInput{
			OrganizationId: organizationId,
			Id:             id,
			Name:           name,
			Description:    description,
		},
	}
	var err error

	var data updateProjectResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
